### PR TITLE
Update the dependency APNG Optimizer to 1.4 and Support Windows build with MinGW

### PR DESCRIPTION
**Pull request by dreampiggy**
1. The dependency apng2webp_apngopt is based on APNG Optimizer 1.2, but it use some undefied behavior of Linux GCC, which is buggy and ouput empty image after being compiled with MinGW GCC. For Windows support, I update this to the latest 1.4 version and also add the patch to animated WebP frame position alignment.
2. Use pbs for WIndows instead of sh module.
3. Use entry_points console_scripts to run CLI script. This is cross-platform support and do not need that symbol link script.
4. Update REAMDME to introduce the Windows build and add detailed description for CLI args.

### CODE REVIEW

**Comment by dreampiggy** [comment]
For that nearly 90's `7z` and `zopfli` file diff changes, it comes from the [APNG Optimizer 1.4](https://sourceforge.net/projects/apng/files/APNG_Optimizer/1.4/) without any modification. You can ignore them.

Also, Due to cross-platform compiler issue and the fact that 7z source file are not distributed as a standalone library. I thnk it's better to keep them as source file.

**Comment by Benny-** [comment]
Thank you for this pull request! It is great to support biggest 3 operating systems now. It will take me some time to review it and test some things. I will accept or provide some comments between tomorrow and next week.

**Comment by Benny-** [comment]
I am having some trouble with a few test files. Can you confirm them?

[This](https://bennyjacobs.nl/tmp/apng2webp/examples/angstybloom.png) one seems to run forever (or for a too long time). And [this](https://bennyjacobs.nl/tmp/apng2webp/examples/coffee.png) gives the following error during the call to webpmux:

ERROR (WEBP_MUX_INVALID_ARGUMENT): Could not add a frame at index 3

[Here](https://bennyjacobs.nl/tmp/apng2webp/examples/) are all the files I tested it with.

I am merging this anyway because this provides windows support. I am also adding you to the developers list so you can directly push.

The huge `7z` and `zopfli` blops align with what is in APNG Optimizer 1.4.

**Comment by dreampiggy** [comment]
@Benny- I will try to fix those issues as soon. Maybe it's because of the new version APNG Optimizer. Also thanks for your invitation and now I can checkout an develop branch.

**Comment by dreampiggy** [comment]
@Benny- Sorry it's my mistake. The patched APNG Optimizer 1.2 close the dispose previous process in source code. But I forget to do this. Accoring to WebP standard, it only support dispose none and dispose background, I fix it and tested these two APNG files and now it works well. PR is here: #6

Meanwhile, I found that APNG Optimizer take more time to process because it now provide 3 compress algorithm(7z, zlib, zopli). But actually we just don't need this compress because the next process APNG Deassembler will extract all PNG frames. I will try to disable it and modify source code to remove dependency to `7z` and `zopli`

**Pull request merged**
