### PR TITLE
fix apngopt process issue

### PR DESCRIPTION
**Pull request by dreampiggy**
WebP does not support dispose previous, so we should not use this optimization

### CODE REVIEW

**Comment by dreampiggy** [comment]
Because we use APNG Optimizier just for optimization for each frame, and then use extracted PNG files to generate static WebP images and finally exec `webpmux`. Therefore we do not need to waste time on any compress level. I remove the dependency to `7z` and `zopli`.

**Comment by dreampiggy** [comment]
That test image `coffee.png` converted to `coffee.webp` now reduce size from 543KB to 533KB, I think this version of APNG Optimizier is better than old version(but also allow Windows MinGW build).

[coffee.webp.zip](https://github.com/Benny-/apng2webp/files/1133587/coffee.webp.zip)

**Comment by Benny-** [comment]
You had a develop branch and pushed in my master. I think you where trying to make a develop branch on my side. But I'm using master as a develop branch and using tags every time a new version for consumption is released. So I'm okay with what just happened.

**Comment by dreampiggy** [comment]
@Benny- You use git tag to keep release is correct. And we should always do that to keep a release a release(Anyone can get the same code whenever cloned).

And I think, for `master` branch, it's OK if you treat it as an `develop` branch and push directly to master. But if there are two or more feaetures or bugs developing at the sametime, we can use multiple branches such as `feature_windows_support` and `fix_decode_bug`, and then create an merge request to `master` to keep no more extra conflict. After merged, you can safely remove that `feature_windows_support` or `fix_decode_bug` branch.

**Pull request merged**
