### PR TITLE
removing install requirements

### PR DESCRIPTION
**Pull request by nnmrts**
`python ./setup.py install` in Python 2.7.12, Windows 10 throws this error

```
Traceback (most recent call last):
  File "./setup.py", line 9, in <module>
    reqs = [str(ir.req) for ir in install_reqs]
  File "C:\Python27\lib\site-packages\pip\req\req_file.py", line 79, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

removing the install requirements fixed it

### CODE REVIEW

**Comment by Benny-** [comment]
nooo

The dependencies need to be installed. It would be better to figure out why parse_requirements() is complaining.

**Comment by nnmrts** [comment]
added another change, i think this works now for everyone

**Comment by Benny-** [comment]
Looks better. I'm still checking it out before merging it. Have you ran the program on windows already and verified it worked?

**Comment by nnmrts** [comment]
@Benny- 
yep, it works on windows, i tried it out :)

sorry for my first commit, i'm learning python at the moment 😆 
<hr>
and just an explanation for my second commit (i "fixed" there two things):

firstly, **`parse_requirements`** needs a **`session`** argument, at least on windows, so i imported **`pip`** and added the missing argument like here: https://github.com/juanpabloaj/pip-init/issues/11

secondly, with using **`os`**, it is checking which system the user works on...
if on nt (windows), then use **`pbs`**, because **`sh`** is not supported on windows
if not, then use **`sh`**

(i don't know if the second "fix" is necessary and what **`sh`** or **`pbs`** exactly are, but when using **`sh`** on windows it throws an error that **`sh`** is only supported on linux and mac and recommends using **`pbs`** as an alternative)

**Comment by Benny-** [comment]
`sh` and `pbs` are python packages to execute other programs. Note that `pbs` is no longer supported as listed on [this](https://pypi.python.org/pypi/pbs) site.

The author of `pbs` is the same as `sh`. And according to issue like https://github.com/amoffat/sh/issues/155 there is not much hope of proper windows support.

Pip does not have a external api after some reading so relaying on parse_requirements might be the wrong thing to do. I will create a issue for this.

**Pull request merged**
